name: bus_tracking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^2.0.0
  http: ^1.1.0
  line_awesome_flutter: ^2.0.0
  sticky_grouped_list: ^3.1.0
  flutter_local_notifications: ^15.1.1
  location: ^5.0.3
  recase: ^4.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  permission_handler: ^10.4.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_rating_bar: ^4.0.1
  adaptive_theme: ^3.3.0
  dropdown_button2: ^2.3.8
  gap: ^3.0.1
  collection: ^1.17.2
  go_router: ^10.1.0
  intersperse: ^2.0.0
  faker: ^2.1.0
  geolocator: ^10.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  vector_math: ^2.1.4
  intl: ^0.18.1
  timezone: ^0.9.2
  flutter_datetime_picker: ^1.5.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.0
  build_verify: ^3.1.0
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/animation/
